export const userData = {
  firstName: "John",
  lastName: "Doe",
  fullName: "John Doe",
  password: "StrongPass123",
  username: "john.doe",
  role: "Next.js Developer",
  avatar: "/images/avatars/04.png",
  background: "/images/background.jpeg",
  phoneNumber: "+1 (555) 123-4567",
  email: "john.doe@example.com",
  state: "California",
  country: "United States",
  address: "123 Main Street, Apt 4B",
  zipCode: "90210",
  language: "English",
  timeZone: "PST",
  currency: "USD",
  organization: "Tech Innovations Inc.",
  twoFactorAuth: false,
  loginAlerts: true,
  accountReoveryOption: "email",
} as const;
