export const userData = {
  first_name: "John",
  last_name: "Doe",
  full_name: "John Doe",
  password: "StrongPass123",
  username: "john.doe",
  role: "Next.js Developer",
  avatar: "/images/avatars/04.png",
  background: "/images/background.jpg",
  phone_number: "+1 (555) 123-4567",
  email: "john.doe@example.com",
  state: "California",
  country: "United States",
  address: "123 Main Street, Apt 4B",
  zip_code: "90210",
  language: "English",
  time_zone: "PST",
  currency: "USD",
  organization: "Tech Innovations Inc.",
  two_factor_auth: false,
  login_alerts: true,
  account_reovery_option: "email",
} as const;
