import { ToDoType } from "../_components/data-table";

export async function getTodosdata(): Promise<ToDoType[]> {
  return [
    {
      id: "1",
      title: "Fix login bug",
      description: "Resolve issue with incorrect login validation",
      label: "bug",
      status: "in progress",
      priority: "high",
      due_date: new Date("2024-10-01"),
      created_at: new Date("2024-09-01"),
      updated_at: new Date("2024-09-10"),
    },
    {
      id: "2",
      title: "Add password reset feature",
      description: "Implement password reset functionality",
      label: "feature",
      status: "todo",
      priority: "medium",
      due_date: new Date("2024-10-05"),
      created_at: new Date("2024-09-02"),
      updated_at: new Date("2024-09-12"),
    },
    {
      id: "3",
      title: "Update API documentation",
      label: "documentation",
      status: "backlog",
      priority: "low",
      created_at: new Date("2024-09-03"),
      updated_at: new Date("2024-09-03"),
    },
    {
      id: "4",
      title: "Test new deployment process",
      label: "feature",
      status: "done",
      priority: "medium",
      created_at: new Date("2024-09-04"),
      updated_at: new Date("2024-09-18"),
    },
    {
      id: "5",
      title: "Cancel outdated migration plan",
      description: "The plan is no longer relevant",
      label: "feature",
      status: "canceled",
      priority: "low",
      created_at: new Date("2024-09-05"),
      updated_at: new Date("2024-09-10"),
    },
    {
      id: "6",
      title: "Fix search bar UI bug",
      description: "Search bar overlaps other elements on mobile view",
      label: "bug",
      status: "backlog",
      priority: "medium",
      created_at: new Date("2024-09-06"),
      updated_at: new Date("2024-09-06"),
    },
    {
      id: "7",
      title: "Improve caching strategy",
      label: "feature",
      status: "in progress",
      priority: "high",
      due_date: new Date("2024-10-07"),
      created_at: new Date("2024-09-07"),
      updated_at: new Date("2024-09-15"),
    },
    {
      id: "8",
      title: "Create API for user data export",
      label: "feature",
      status: "todo",
      priority: "medium",
      created_at: new Date("2024-09-08"),
      updated_at: new Date("2024-09-10"),
    },
    {
      id: "9",
      title: "Document installation process",
      label: "documentation",
      status: "done",
      priority: "low",
      created_at: new Date("2024-09-09"),
      updated_at: new Date("2024-09-20"),
    },
    {
      id: "10",
      title: "Refactor authentication module",
      description: "Improve maintainability of authentication code",
      label: "feature",
      status: "in progress",
      priority: "high",
      created_at: new Date("2024-09-10"),
      updated_at: new Date("2024-09-18"),
    },
    {
      id: "11",
      title: "Fix image upload issue",
      label: "bug",
      status: "backlog",
      priority: "medium",
      created_at: new Date("2024-09-11"),
      updated_at: new Date("2024-09-11"),
    },
    {
      id: "12",
      title: "Redesign profile page",
      label: "feature",
      status: "todo",
      priority: "low",
      created_at: new Date("2024-09-12"),
      updated_at: new Date("2024-09-12"),
    },
    {
      id: "13",
      title: "Automate deployment pipeline",
      label: "feature",
      status: "done",
      priority: "high",
      created_at: new Date("2024-09-13"),
      updated_at: new Date("2024-09-19"),
    },
    {
      id: "14",
      title: "Fix email notification delays",
      label: "bug",
      status: "in progress",
      priority: "high",
      due_date: new Date("2024-10-11"),
      created_at: new Date("2024-09-14"),
      updated_at: new Date("2024-09-18"),
    },
    {
      id: "15",
      title: "Update user settings design",
      label: "feature",
      status: "canceled",
      priority: "medium",
      created_at: new Date("2024-09-15"),
      updated_at: new Date("2024-09-16"),
    },
    {
      id: "16",
      title: "Fix scroll issue on Safari",
      label: "bug",
      status: "backlog",
      priority: "low",
      created_at: new Date("2024-09-16"),
      updated_at: new Date("2024-09-16"),
    },
    {
      id: "17",
      title: "Enhance security for login",
      label: "feature",
      status: "in progress",
      priority: "high",
      due_date: new Date("2024-10-13"),
      created_at: new Date("2024-09-17"),
      updated_at: new Date("2024-09-20"),
    },
    {
      id: "18",
      title: "Add two-factor authentication",
      label: "feature",
      status: "todo",
      priority: "medium",
      created_at: new Date("2024-09-18"),
      updated_at: new Date("2024-09-18"),
    },
    {
      id: "19",
      title: "Write tests for API endpoints",
      label: "documentation",
      status: "done",
      priority: "medium",
      created_at: new Date("2024-09-19"),
      updated_at: new Date("2024-09-21"),
    },
    {
      id: "20",
      title: "Fix database connection pool issues",
      label: "bug",
      status: "backlog",
      priority: "high",
      created_at: new Date("2024-09-20"),
      updated_at: new Date("2024-09-20"),
    },
    {
      id: "21",
      title: "Optimize image loading speed",
      label: "feature",
      status: "in progress",
      priority: "medium",
      due_date: new Date("2024-10-14"),
      created_at: new Date("2024-09-21"),
      updated_at: new Date("2024-09-22"),
    },
    {
      id: "22",
      title: "Refactor payment processing module",
      label: "feature",
      status: "todo",
      priority: "high",
      created_at: new Date("2024-09-22"),
      updated_at: new Date("2024-09-22"),
    },
    {
      id: "23",
      title: "Improve error logging system",
      label: "feature",
      status: "in progress",
      priority: "medium",
      created_at: new Date("2024-09-23"),
      updated_at: new Date("2024-09-25"),
    },
    {
      id: "24",
      title: "Update README documentation",
      label: "documentation",
      status: "done",
      priority: "low",
      created_at: new Date("2024-09-24"),
      updated_at: new Date("2024-09-25"),
    },
    {
      id: "25",
      title: "Fix mobile view navbar",
      label: "bug",
      status: "backlog",
      priority: "low",
      created_at: new Date("2024-09-25"),
      updated_at: new Date("2024-09-25"),
    },
    {
      id: "26",
      title: "Implement OAuth login",
      label: "feature",
      status: "todo",
      priority: "high",
      created_at: new Date("2024-09-26"),
      updated_at: new Date("2024-09-26"),
    },
    {
      id: "27",
      title: "Fix bug in order processing flow",
      label: "bug",
      status: "in progress",
      priority: "high",
      due_date: new Date("2024-10-16"),
      created_at: new Date("2024-09-27"),
      updated_at: new Date("2024-09-28"),
    },
    {
      id: "28",
      title: "Improve dashboard analytics",
      label: "feature",
      status: "todo",
      priority: "medium",
      created_at: new Date("2024-09-28"),
      updated_at: new Date("2024-09-28"),
    },
    {
      id: "29",
      title: "Fix bug in export report",
      label: "bug",
      status: "done",
      priority: "high",
      created_at: new Date("2024-09-29"),
      updated_at: new Date("2024-09-29"),
    },
    {
      id: "30",
      title: "Update onboarding guide",
      label: "documentation",
      status: "in progress",
      priority: "low",
      created_at: new Date("2024-09-30"),
      updated_at: new Date("2024-10-01"),
    },
    {
      id: "31",
      title: "Fix crashing issue on checkout",
      label: "bug",
      status: "todo",
      priority: "high",
      created_at: new Date("2024-09-30"),
      updated_at: new Date("2024-10-01"),
    },
    {
      id: "32",
      title: "Optimize search queries",
      label: "feature",
      status: "in progress",
      priority: "medium",
      created_at: new Date("2024-09-22"),
      updated_at: new Date("2024-09-23"),
    },
    {
      id: "33",
      title: "Revamp dashboard UI",
      label: "feature",
      status: "backlog",
      priority: "medium",
      created_at: new Date("2024-09-24"),
      updated_at: new Date("2024-09-24"),
    },
    {
      id: "34",
      title: "Fix file upload timeout",
      label: "bug",
      status: "done",
      priority: "high",
      created_at: new Date("2024-09-26"),
      updated_at: new Date("2024-09-27"),
    },
    {
      id: "35",
      title: "Improve error messages",
      label: "feature",
      status: "in progress",
      priority: "medium",
      created_at: new Date("2024-09-18"),
      updated_at: new Date("2024-09-19"),
    },
    {
      id: "36",
      title: "Fix minor UI bug in sidebar",
      label: "bug",
      status: "backlog",
      priority: "low",
      created_at: new Date("2024-09-20"),
      updated_at: new Date("2024-09-20"),
    },
    {
      id: "37",
      title: "Add new analytics reports",
      label: "feature",
      status: "todo",
      priority: "medium",
      created_at: new Date("2024-09-30"),
      updated_at: new Date("2024-09-30"),
    },
    {
      id: "38",
      title: "Fix dark mode toggle issue",
      label: "bug",
      status: "in progress",
      priority: "medium",
      created_at: new Date("2024-09-21"),
      updated_at: new Date("2024-09-25"),
    },
    {
      id: "39",
      title: "Update accessibility options",
      label: "feature",
      status: "done",
      priority: "low",
      created_at: new Date("2024-09-15"),
      updated_at: new Date("2024-09-22"),
    },
    {
      id: "40",
      title: "Fix layout shift on home page",
      label: "bug",
      status: "in progress",
      priority: "high",
      created_at: new Date("2024-09-12"),
      updated_at: new Date("2024-09-18"),
    },
  ];
}
