name: UI/UX Feedback
description: Share feedback about layout, usability, or design
labels: [ui]
title: "[ui] "

body:
  - type: textarea
    id: feedback
    attributes:
      label: Describe the issue or suggestion
      description: Be as detailed as possible. Feel free to include screenshots or mockups.
    validations:
      required: true
